### ISSUE TITLE
Can we use celery as PUB/SUB?

### ISSUE THREAD

**Issue by fadishaar84** [permitio/fastapi_websocket_pubsub#28]
I'm wondering whether we can use celery+rabbitmq as PUB/SUB and what modifications need to be done to achieve this? Thank you.

**Comment by orweis** [comment]
Hey there Fadi :) 

If you mean to use celery/rabbitmq as a backbone pub/sub (instead of Kafka, Redis, Postgres L/N), then yes there's a way - though it's not as straightforward as we'd like.

Fastapi-ws-PubSub uses [Broadcaster](https://github.com/encode/broadcaster) as an adapter to the backbone pub-sub.
You can rather easily implement a celery/rabbitmq adapter there,[ see the implementations here ](https://github.com/encode/broadcaster/tree/master/broadcaster/_backends) 

The challenge would be to make broadcaster aware of your new backend (since the[ importing the backends is hardcoded here](https://github.com/encode/broadcaster/blob/master/broadcaster/_base.py))

Unfortunately it seems that the maintainers of broadcaster are not responsive - so you might find a hard time getting your pull request there.

A hack you can use (Which I'm not a fan of) is to create a Broadcaster instance and override its  self._backend.
And of course you can fork broadcaster and do as you wish...

Hope this helps. :)

**Comment by asafc** [comment]
Closing this issue as this should be addressed by [encode/broadcaster](https://github.com/encode/broadcaster)
